server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-spring-mouse-an7xrp4l-pooler.c-6.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Hq7wk6OIfUdh

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect